### ISSUE TITLE
Can we make NPC's stop so we can talk to them

### ISSUE THREAD

**Issue by IsaacTestUser** [IsaacMulcahy/RPG-AI-SYSTEM-WIKI#1]
**Is your feature request related to a problem? Please describe.**

I want to be able to pause my NPC's where they are so I can chat to them

**Describe the solution you'd like**

Could we just pause what they are doing and run the idle animation?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by IsaacMulcahy** [comment]
This will be looked into this week and a time frame will be provided if the feature is decided to be added

**Comment by IsaacMulcahy** [comment]
This has been coded, tested and ready for production. Will bundle with some other features with a release. Wiki will need updating
