### ISSUE TITLE
BUG - Build errors 

### ISSUE THREAD

**Issue by GamePowerDev** [IsaacMulcahy/RPG-AI-SYSTEM-WIKI#4]
**Describe the bug**
Projects cannot build with Civil AI System

**To Reproduce**
1. Import Civil AI System
2. Build Project
3. See error

**Expected behavior**
Should be able to build project

**Screenshots**
![2022-10-11](https://user-images.githubusercontent.com/79423936/195176803-2ef4e755-53fa-4284-8254-e6a292281c91.png)

**Additional context**
All classes that utilize unity Editor namespace should have #if UNITY_EDITOR wrapped around the code.

This doesn't break anything while developing, only when trying to build.

**Comment by IsaacMulcahy** [comment]
Hi GamePowerDev, sorry that this has happened, will take a look into this right now and get back asap

**Comment by IsaacMulcahy** [comment]
Thanks for providing the solution in the *Additional context*, I've updated and submitted a new release request. I've also added in the 'pause' feature as a means to allow for the chat functionality ([Wiki desc here](https://github.com/IsaacMulcahy/RPG-AI-SYSTEM-WIKI/wiki/Customizing-The-System#chat-system)) you asked to be added along with another small but useful feature.

**Comment by IsaacMulcahy** [comment]
Just wanted to update - Added feature and fix were both submitted to Unity two days ago, will expect the change to be released early next week

**Comment by IsaacMulcahy** [comment]
Has been release V0.1.2
