### ISSUE TITLE
Apostrophes

### ISSUE THREAD

**Issue by StreborDaerd** [IsaacMulcahy/RPG-AI-SYSTEM-WIKI#9]
Plural nouns don't use apostrophes.

Apostrophes are used when contracting "noun + is" to "noun's".
Example - "the NPC is walking somewhere" to "the NPC's walking somewhere". This refers to a single NPC.

Apostrophes are also used when showing possession of an object or trait by a noun.
Example "the NPC's hitpoints are low". This refers to a single NPC.

For plurals (more than one of something)
"The NPCs are walking somewhere" refers to multiple NPCs. Notice there is no apostrophe.
"All the NPCs' hitpoints are low" refer to multiple NPCs with low hitpoints. Notice the apostrophe comes after the "s".

When using "it's" and "its", the first is a contraction of "it is", the second is the possessive.
Contraction example - "it is walking somewhere" contracts to "it's walking somewhere".
Possessive example - "its hitpoints are low".

**Comment by IsaacMulcahy** [comment]
Thanks for reporting this, will have a look at fixing this within the next Update!

**Comment by IsaacMulcahy** [comment]
Hey Strebor, 

Just wanted to let you know I have made the fix to the Asset Store page and the package (will be coming out soon). 

Let me know if I've missed anything! Also thanks for letting me know!
